#!/bin/sh
# {{ ansible_managed }}

{{ dehydrated_pre_cronjob }}

{% if dehydrated_version == 'git' %}{{ dehydrated_basedir }}/dehydrated{% else %}/usr/bin/dehydrated{% endif %} --cron > {{ dehydrated_updatelog }} 2>&1 && (
{% for service in dehydrated_reload_services %}
service {{ service }} reload;
{% endfor %} )

{{ dehydrated_post_cronjob }}
