#!/bin/sh
# {{ ansible_managed }}

{{dehydrated_basedir}}/dehydrated --cron > {{dehydrated_updatelog}} 2>&1 || ( \
{% for service in dehydrated_reload_services %}
service {{ service }} reload;
{% endfor %} )
